GaleriaDeArte/Models/Lance.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GaleriaDeArte.Models
{
    public class Lance
    {
        [Display(Name = "#")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Este campo é obrigatório")]
        [Display(Name ="Nome completo")]
        public string Nome { get; set; }

        [Display(Name = "CPF (XXX.XXX.XXX-XX)")]
        [Required(ErrorMessage = "Este campo é obrigatório")]
        [StringLength(14)]
        public string CPF { get; set; }

        [Display(Name = "Lance (em milhões de R$)")]
        [Required(ErrorMessage = "Este campo é obrigatório")]
        public double Proposta { get; set; }

        [Required(ErrorMessage = "Lance deve possuir uma obra de arte")]
        [Display(Name = "Obra")]
        public int? ObraId { get; set; }

        public Obra Obra { get; set; }

        public string UserId { get; set; }

        public IdentityUser User { get; set; }
    }
}

GaleriaDeArte/Controllers/LanceController.cs
using GaleriaDeArte.Models;
using GaleriaDeArte.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GaleriaDeArte.Controllers
{
    public class LanceController : Controller
    {
        ILanceService _service;
        ObraSqlService _obraSql;
        
        public LanceController(ILanceService serviceSql, ObraSqlService obraSql)
        {
            _service = serviceSql;
            _obraSql = obraSql;
        }

        public IActionResult Index(string busca, bool ordenar)
        {
            return View(_service.GetAll(User.Identity.Name));        
        }


        [HttpGet]
        public IActionResult Create(string busca, bool ordenar)
        {
            var obras = _obraSql.GetAll(busca, ordenar);
            ViewBag.listaDeObras = new SelectList(obras, "Id", "Nome"); // Nessa hora que a gente mostra o nome ao invés do ID.
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // só devemos inserir nos métodos post, para validar o token.
        public IActionResult Create(Lance lance, string busca, bool ordenar)
        {
            var obras = _obraSql.GetAll(busca, ordenar);
            ViewBag.listaDeObras = new SelectList(obras, "Id", "Nome"); // Nessa hora que a gente mostra o nome ao invés do ID.

            if (!ModelState.IsValid) return View(lance);

            if (_service.Create(lance, User.Identity.Name))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(lance);
            }
        }            

        
        public IActionResult Read(int? id)
        {
            Lance lance = _service.Get(id);
            return lance != null ?
                View(lance) :
                NotFound();
        }

        
        public IActionResult Update(int? id, string busca, bool ordenar)
        {
            var obras = _obraSql.GetAll(busca, ordenar);
            ViewBag.listaDeObras = new SelectList(obras, "Id", "Nome"); // Nessa hora que a gente mostra o nome ao invés do ID.

            Lance lance = _service.Get(id);
            return lance != null ?
                View(lance) :
                NotFound();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Lance lance, string busca, bool ordenar)
        {
            var obras = _obraSql.GetAll(busca, ordenar);
            ViewBag.listaDeObras = new SelectList(obras, "Id", "Nome"); // Nessa hora que a gente mostra o nome ao invés do ID.

            if (!ModelState.IsValid) return View(lance); //validaçao

            if (_service.Update(lance)) //// PacienteStaticService.Create(paciente)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(lance);
            }
        }

        
        public IActionResult Delete(int? id)
        {
            if (_service.Delete(id)) 
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }       

        
        public IActionResult Confirm(Lance lance)
        {
            ViewBag.obra = lance.Id;
            ViewBag.confirm = "Tem certeza que deseja deletar este lance?";
            return View();
        }
    }
}

GaleriaDeArte/Views/Lance/Confirm.cshtml
@{
    ViewData["Title"] = "Deletar";
}

<h1 class="bg-danger text-center">@ViewBag.confirm</h1>

<a class="btn btn-outline-danger text-center" asp-controller="Lance" asp-action="Delete" asp-route-id="@ViewBag.obra">Deletar</a>
<a class="btn btn-outline-dark" asp-controller="Lance" asp-action="Index">Voltar</a>

GaleriaDeArte/Views/Lance/Create.cshtml
@{
    ViewData["Title"] = "Novo Lance";
}
@model Lance

<h1>Insira uma nova obra</h1>

<div class="row">
    <form class="col-md-4" asp-action="Create">
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control"/>
            <span class="text-warning" asp-validation-for="Nome"></span>
        </div>
        <div class="form-group">
            <label asp-for="CPF" class="control-label"></label>
            <input asp-for="CPF" class="form-control" />
            <span class="text-warning" asp-validation-for="CPF"></span>
        </div>
        <div class="form-group">
            <label asp-for="Proposta" class="control-label"></label>
            <input asp-for="Proposta" class="form-control" />
            <span class="text-warning" asp-validation-for="Proposta"></span>
        </div>
        <div class="form-group">
            <label asp-for="ObraId" class="control-label"></label>
            <select asp-for="ObraId" class="form-control" asp-items="ViewBag.ListaDeObras">
                <option value=""> -- Selecione -- </option>
            </select>

            <span class="text-warning" asp-validation-for="ObraId"></span>
        </div>
        <div class="form-group">
            <input class="btn btn-danger" type="submit" value="Enviar"/>
            <a class="btn btn-info" asp-controller="Lance" asp-action="Index">Voltar</a>

        </div>
    </form>
</div>

GaleriaDeArte/Views/Lance/Index.cshtml
@{
    ViewData["Title"] = "Lances"; /* Mantive aqui para ficar bonito no nome da aba*/
}

@model List<Lance>

<h1 class="shadow-lg"> Lista de lances</h1>
<br />
<form class="row">
    <div>
        <a class="btn btn-outline-dark" asp-controller="Home" asp-action="Index">Voltar</a>
        <a class="btn btn-outline-danger" asp-controller="Lance" asp-action="Create">Novo Lance</a>
    </div>
</form>
<br />


<table class="table table-secondary">
    <thead>
        <tr>
            <th class="text-center">@Html.DisplayNameFor(Model => Model.First().Id)</th>
            <th class="text-center">@Html.DisplayNameFor(Model => Model.First().Nome)</th>
            <th class="text-center">@Html.DisplayNameFor(Model => Model.First().CPF)</th>
            <th class="text-center">@Html.DisplayNameFor(Model => Model.First().Obra.Nome)</th>
            <th class="text-center">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Lance lance in Model)@*O Model aqui é outra forma de mostrar os dados, ao invés da ViewBag*@
        {
            <tr>
                <td class="text-center">@Html.DisplayFor(Model => lance.Id)</td> @*mostre como deve ser apresentado o atributo conforme o meu model*@
                <td class="text-center">@Html.DisplayFor(Model => lance.Nome)</td>
                <td class="text-center">@Html.DisplayFor(Model => lance.CPF)</td>
                <td class="text-center">@Html.DisplayFor(Model => lance.Obra.Nome)</td>
                <td>

                    <a asp-controller="Lance" asp-action="Read" asp-route-id="@lance.Id">Visualizar</a>
                    <span> | </span>
                    <a asp-controller="Lance" asp-action="Update" asp-route-id="@lance.Id">Atualizar</a>
                    <span> | </span>
                    <a asp-controller="Lance" asp-action="Confirm" asp-route-id="@lance.Id">Deletar</a>

                </td>
            </tr>
        }
    </tbody>
</table>

GaleriaDeArte/Views/Lance/Read.cshtml
@{
    ViewData["Title"] = "Leitura";
}

@model Lance

<dt class="list-group-item active" aria-current="true">Visualizando Lance @Model.Id</dt>
<br />
<dl class="row">
    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Id)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Id)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Nome)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Nome)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.CPF)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.CPF)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Proposta)</dt>
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Proposta)</dd>

    <dt class="col-sm-3">@Html.DisplayNameFor(Model => Model.Obra.Nome)</dt> 
    <dd class="col-sm-9">@Html.DisplayFor(Model => Model.Obra.Nome)</dd>
</dl>

    <a class="btn btn-outline-dark" asp-controller="Lance" asp-action="Index">Voltar</a>

GaleriaDeArte/Views/Lance/Update.cshtml
@{
    ViewData["Title"] = "Atualizar";
}

@model Lance

<h4 class="list-group-item active" aria-current="true">Atualizar Lance</h4>
<br />

<div class="row">
    <form class="col-md-4" asp-action="Update">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="CPF" class="control-label"></label>
            <input asp-for="CPF" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Proposta" class="control-label"></label>
            <input asp-for="Proposta" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="ObraId" class="control-label"></label>
            <select asp-for="ObraId" class="form-control" asp-items="ViewBag.ListaDeObras">
                <option value=""> -- Selecione -- </option>
            </select>
        </div>
        <div class="form-group">
            <input class="btn btn-outline-danger" type="submit" value="Atualizar" />
            <a class="btn btn-outline-dark" asp-controller="Lance" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>