GaleriaDeArte/Models/Obra.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GaleriaDeArte.Models
{
    public class Obra
    {
        [Display(Name = "#")]
        public int Id { get; set; }

        [Display(Name = "Imagem")]
        public string Imagem { get; set; }

        [Required(ErrorMessage = "Informe um título para a obra")]
        [Display(Name = "Título")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Informe o autor da obra")]
        [Display(Name = "Autor")]
        public string Autor { get; set; }

        [Display(Name = "Sobre")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "Preço da obra é obrigatório")]
        [Display(Name ="Valor (em milhões de R$)")]
        public double? Preco { get; set; }

        [Required(ErrorMessage = "Informe a data da criação da obra")]
        [Display(Name = "Data da Obra")]
        [DataType(DataType.Date)]
        public DateTime? Data { get; set; }

        public List<Lance> Lances { get; set; }
    }
}

GaleriaDeArte/Controllers/ObraController.cs
using GaleriaDeArte.Models;
using GaleriaDeArte.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace GaleriaDeArte.Controllers
{
    public class ObraController : Controller
    {
        IObraService _service, _serviceSql, _serviceStatic, _serviceTudo;
        
        public ObraController(ObraSqlService serviceSql, ObraStaticService serviceStatic, ObraFullService serviceTudo)
        {
            _serviceSql = serviceSql;
            _serviceStatic = serviceStatic;
            _serviceTudo = serviceTudo;
            _service = serviceSql;
        }

        public void SelectService(string service = "sql")
        {
            switch (service)
            {
                case "static":
                    this._service = this._serviceStatic;
                    break;
                case "both":
                    this._service = this._serviceTudo;
                    break;
                default:
                    this._service = this._serviceSql;
                    break;
            }
        }

        public IActionResult Index(string busca, bool ordenar = false, string service = "sql")
        {
            SelectService(service);

            ViewBag.ordenar = ordenar;
            ViewBag.total = _service.GetAll(busca, ordenar).Count;
            ViewBag.valortotal = _service.GetAll(busca, ordenar).Count == 0 ? default : _service.GetAll(busca, ordenar).Sum(p => p.Preco);
            ViewBag.maisAntiga = _service.GetAll(busca, ordenar).Count == 0 ? default : _service.GetAll(busca, ordenar).Find(o => o.Data == _service.GetAll(busca, ordenar).Max(p => p.Data)).Nome;
            ViewBag.maisCara = _service.GetAll(busca, ordenar).Count == 0 ? default : _service.GetAll(busca, ordenar).Find(o => o.Preco == _service.GetAll(busca, ordenar).Max(p => p.Preco)).Nome;
            ViewBag.service = service;
            ViewBag.busca = busca;
            return View(_service.GetAll(busca, ordenar));
                       

            //List<Obra> lista = getObras();
            //List<Obra> lista = _context.Obra.ToList(); // No meu contexto, pegue a tabela do meu Modelo e traga para uma lista.
            //if (ordenar) // Vousempre comparar os meus elementos, sempre de dois em dois, sabendo qual fica antes e qual depois.
            //{                
            //    // o método CompareTo() vai ver ser se a string que estou pasando dentro está antes, igual ou depois.
            //    lista = lista.OrderBy(o => o.Nome).ToList(); // ordenar a lista por um campo específico (nome). Dentro dele são dois parâmetros. Comparando nome da ObraA com a ObraB e já vai ordenando.
                
            //    return View(lista);
            //    //lista = lista.OrderBy(o => o.Nome).ToList();
            //    //return View(lista); Essa é outra forma de se fazer. Esseé mais fácil de entender
            //}

            //List<Obra> obras = busca != null ? lista.FindAll(o => o.Nome.ToUpper().Contains(busca.ToUpper())) : lista;
            //ViewBag.total = obras.Count();
            //ViewBag.valortotal = obras.Sum(o => o.Preco);
            //return View(obras); // tenho que passar os dados aqui para ter o que mostrar na index através do Model.           
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken] // só devemos inserir nos métodos post, para validar o token.
        public IActionResult Create(Obra obra)
        {
            if (!ModelState.IsValid) return View(obra);

            if (_service.Create(obra))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(obra);
            }
        }            

        public IActionResult Read(int? id)
        {
            Obra obra = _service.Get(id);
            return obra != null ?
                View(obra) :
                NotFound();
        }

        [Authorize]
        public IActionResult Update(int? id)
        {
            Obra obra = _service.Get(id);
            return obra != null ?
                View(obra) :
                NotFound();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Obra obra)
        {
            if (!ModelState.IsValid) return View(obra); //validaçao

            if (_service.Update(obra)) //// PacienteStaticService.Create(paciente)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(obra);
            }
        }

        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (_service.Delete(id)) 
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }       

        [Authorize]
        public IActionResult Confirm(Obra obra)
        {
            ViewBag.obra = obra.Id;
            ViewBag.confirm = "Tem certeza que deseja deletar esta obra?";
            return View();
        }
    }
}

GaleriaDeArte/Views/Obra/Confirm.cshtml
@{
    ViewData["Title"] = "Deletar";
}

<h1 class="bg-danger text-center">@ViewBag.confirm</h1>

<a class="btn btn-outline-danger text-center" asp-controller="Obra" asp-action="Delete" asp-route-id="@ViewBag.obra">Deletar</a>
<a class="btn btn-outline-dark" asp-controller="Obra" asp-action="Read">Voltar</a>

GaleriaDeArte/Views/Obra/Create.cshtml
@{
    ViewData["Title"] = "Nova Obra";
}
@model Obra

<h1>Insira uma nova obra</h1>

<div class="row">
    <form class="col-md-4" asp-action="Create">
        <div class="form-group">
            <label asp-for="Imagem" class="control-label"></label>
            <input asp-for="Imagem" class="form-control"/>
            <span class="text-warning" asp-validation-for="Imagem"></span>
        </div>
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
            <span class="text-warning" asp-validation-for="Nome"></span>
        </div>
        <div class="form-group">
            <label asp-for="Autor" class="control-label"></label>
            <input asp-for="Autor" class="form-control" />
            <span class="text-warning" asp-validation-for="Autor"></span>
        </div>
        <div class="form-group">
            <label asp-for="Descricao" class="control-label"></label>
            <input asp-for="Descricao" class="form-control" />
            <span class="text-warning" asp-validation-for="Descricao"></span>
        </div>
        <div class="form-group">
            <label asp-for="Preco" class="control-label"></label>
            <input asp-for="Preco" class="form-control" />
            <span class="text-warning" asp-validation-for="Preco"></span>
        </div>
        <div class="form-group">
            <label asp-for="Data" class="control-label"></label>
            <input asp-for="Data" class="form-control" />
            <span class="text-warning" asp-validation-for="Data"></span>
        </div>
        <div class="form-group">
            <input class="btn btn-danger" type="submit" value="Enviar"/>
            <a class="btn btn-info" asp-controller="Obra" asp-action="Index">Voltar</a>

        </div>
    </form>
</div>

GaleriaDeArte/Views/Obra/Index.cshtml
@{
    ViewData["Title"] = "Obras"; /* Mantive aqui para ficar bonito no nome da aba*/
}

@model List<Obra>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<h1 class="shadow-lg"> Acervo de obras</h1>
<br />
<form class="row">
    <div class="col col-md-4">
        <input type="text" class="form-control" name="busca" placeholder="Pesquisar por nome" />
        &nbsp; &nbsp;
        <br />
        <select name="service" class="form-select" aria-label="Default select example">
            <option value="sql">Banco de Dados - SQL</option>
            <option value="static">Dados Estáticos</option>
            <option value="both">Ambos</option>
        </select>
<br />
    </div>
    <div class="col col-md-8">
        <button type="submit" class="btn btn-outline-dark">Pesquisar</button>
        <a class="btn btn-outline-dark" asp-controller="Home" asp-action="Index">Voltar</a>


        @if (ViewBag.ordenar == true)
        {
            <a asp-action="Index" class="btn btn-outline-primary">Reordenar por Id</a>
        }
        else
        {
            <a href="/Obra/Index?ordenar=true" class="btn btn-outline-info">Ordenar Títulos</a>
        }

        
    </div>
</form>
<br />

@if (ViewBag.total < ViewBag.inicial)
{
    <p class="text-center alert alert-danger" role="alert">Obra @ViewBag.info deletada com sucesso!</p>
}


@if (@ViewBag.id > 10)
{
    <div class="alert alert-success" role="alert">Obra cadastrada com sucesso!</div>
}



<table class="table table-secondary">
    <thead>
        <tr>
            <th class="text-center">@Html.DisplayNameFor(Model => Model.First().Id)</th>
            <th class="text-center">@Html.DisplayNameFor(Model => Model.First().Nome)</th>
            <th class="text-center">@Html.DisplayNameFor(Model => Model.First().Data)</th>
            <th class="text-center">@Html.DisplayNameFor(Model => Model.First().Preco)</th>
            <th class="text-center">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Obra obra in Model)@*O Model aqui é outra forma de mostrar os dados, ao invés da ViewBag*@
        {
            string qtdLance = obra.Lances.Count > 0 ? $"{obra.Lances.Count}" : "";
            <tr>
                <td class="text-center">@Html.DisplayFor(Model => obra.Id)</td> @*mostre como deve ser apresentado o atributo conforme o meu model*@
                <td class="text-center">@Html.DisplayFor(Model => obra.Nome)<span class="badge bg-warning text-dark ml-2">@qtdLance</span></td>
                <td class="text-center">@Html.DisplayFor(Model => obra.Data)</td>
                <td class="text-center">@Html.DisplayFor(Model => obra.Preco)</td>
                <td>
                    @if (ViewBag.service == "sql")
                    {
                        <a asp-controller="Obra" asp-action="Read" asp-route-id="@obra.Id">Visualizar</a>
                        <span> | </span>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <a asp-controller="Obra" asp-action="Create">Criar</a><span> | </span>
                            <a asp-controller="Obra" asp-action="Update" asp-route-id="@obra.Id">Atualizar</a>
                            <span> | </span>
                            <a asp-controller="Obra" asp-action="Confirm" asp-route-id="@obra.Id">Deletar</a>
                        }
                        else
                        {
                            <a class="text-black-50" asp-area="Identity" asp-page="/Account/Login">Logue para edições</a>
                        }

                    }
                    else
                    {
                        <p>Não há ações para esta fonte de dados!</p>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>

<div class="p-3 mb-2 bg-dark text-white">Quantidade de obras: <span class="badge badge-success text-light"><strong>@ViewBag.total</strong></span></div>
<div class="p-3 mb-2 bg-dark text-white">Valor total das obras: <span class="badge badge-success text-light"><strong>R$ @ViewBag.valortotal milhões</strong></span></div>
<div class="p-3 mb-2 bg-dark text-white">Obra mais recente: <span class="badge badge-success text-light"><strong>@ViewBag.maisAntiga</strong></span></div>
<div class="p-3 mb-2 bg-dark text-white">Obra mais cara: <span class="badge badge-success text-light"><strong>@ViewBag.maisCara</strong></span></div>

GaleriaDeArte/Views/Obra/Read.cshtml
@{
    ViewData["Title"] = "Leitura";
}

@model Obra

<dt class="list-group-item active" aria-current="true">Visualizando Obra @Model.Id</dt>
<br />

<dl class="row">
    <div class="card mb-3" style="max-width: 500px;">
        <div class="row g-0">
            <div class="col-md-10">
                <img src="@Model.Imagem" class="img-fluid rounded-start" alt="">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title">@Model.Nome</h4>
                    <dt class="col-sm-5">@Html.DisplayNameFor(Model => Model.Id)</dt>
                    <dd class="col-sm-12">@Html.DisplayFor(Model => Model.Id)</dd>

                    <dt class="col-sm-5">@Html.DisplayNameFor(Model => Model.Autor)</dt>
                    <dd class="col-sm-12">@Html.DisplayFor(Model => Model.Autor)</dd>

                    <dt class="col-sm-5">@Html.DisplayNameFor(Model => Model.Descricao)</dt>
                    <dd class="col-sm-12">@Html.DisplayFor(Model => Model.Descricao)</dd>

                    <dt class="col-sm-5">@Html.DisplayNameFor(Model => Model.Preco)</dt>
                    <dd class="col-sm-12">@Html.DisplayFor(Model => Model.Preco)</dd>

                    <dt class="col-sm-5">@Html.DisplayNameFor(Model => Model.Data)</dt>
                    <dd class="col-sm-12">@Html.DisplayFor(Model => Model.Data)</dd>
                </div>
            </div>
        </div>
    </div>
</dl>

@if (Model.Lances.Count > 0)
{
    <h2>Lances</h2>
    @foreach (Lance l in Model.Lances)
    {
        <p><strong>@Html.DisplayFor(a => l.Nome)</strong> | R$ @Html.DisplayFor(a => l.Proposta) milhões</p>
    }
}

GaleriaDeArte/Views/Obra/Update.cshtml
@{
    ViewData["Title"] = "Atualizar";
}

@model Obra

<h4>Atualizar Obra</h4>

<div class="row">
    <form class="col-md-4" asp-action="Update">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Imagem" class="control-label"></label>
            <input asp-for="Imagem" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Autor" class="control-label"></label>
            <input asp-for="Autor" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Descricao" class="control-label"></label>
            <input asp-for="Descricao" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Preco" class="control-label"></label>
            <input asp-for="Preco" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Data" class="control-label"></label>
            <input asp-for="Data" class="form-control" />
        </div>
        <div class="form-group">
            <input class="btn btn-outline-danger" type="submit" value="Atualizar" />
            <a class="btn btn-outline-dark" asp-controller="Obra" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>